spring:
  application:
    name: zuul-service

server:
  port: 5662

## 向服务中心注册服务
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#登陆拦截器相关配置
loginFilter:
  enable: true;

#跨域请求拦截器相关配置
tokenFilter:
  enable: true;
