spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://14.116.254.127:13306/manage_task
    username: mysql
    password: mysql123

### redis缓存配置
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 50000
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:9618, 127.0.0.1:9619, 127.0.0.1:9620

### rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

system:
  token: 199518wa123!